#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s `which virtualenvwrapper.sh` ]]; then
  source `which virtualenvwrapper.sh`
fi

alias o=open
alias oo="open ."
alias s="subl"
alias h="history"

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/p

mkdir -p $PROJECT_HOME

alias mc1="ssh kmc1"
alias vc1="ssh kvc1"
alias vc2="ssh kvc2"
alias vcm1="ssh kvcm1"
alias vcm2="ssh kvcm2"